<?php
	// this cron runs each whole hour of the day
    include("/var/www/modules/connectdb.php");
    include("/var/www/modules/settings.php");
    include("/var/www/modules/functions.php");
	//include("/var/www/modules/cronspreadvirus.php");
	include("/var/www/modules/crongw.php");
    include("/var/www/modules/cronftp.php");
	    
    // read economy details
    $result = mysqli_query($link, "SELECT spam_economy, phishing_economy, porn_economy, filesharing_economy FROM economy ORDER BY id DESC LIMIT 1");
    $row = mysqli_fetch_assoc($result);
    $spam_rev = $spamserver_revenue * ($row['spam_economy']/100);
    $phishing_rev = $phishingserver_revenue * ($row['phishing_economy']/100);
    $porn_rev = $pornserver_revenue * ($row['porn_economy']/100);
    $filesharing_rev = $filesharingserver_revenue * ($row['filesharing_economy']/100);

	// how long an FBI ip and password should at least be valid is stored in $fbi_valid_time
	$fbi_serverpass_reset = date($date_format, strtotime("-".$fbi_valid_time." minutes"));
	$fbi_serverip_reset = date($date_format, strtotime("-".$fbi_valid_time." minutes"));
	
    // fill a recordset with hackers who are not banned or npc and online in the past month
    $norevenue = date($date_format, strtotime("-".$no_revenuedays." days"));    
    $result = mysqli_query($link, "SELECT hybernate_till, id, activationcode, banned_date, clan_id, real_ip, alias, ip, last_click FROM hacker WHERE banned_date = 0 AND npc = 0 AND jailed_till < '$now' AND last_click > $norevenue");
    sleep (1);
    // fill a recordset with servers
    $server_result = mysqli_query($link, "SELECT server.id, server.hacker_id, server.product_id, server.product_efficiency, server.efficiency, server.ip FROM server WHERE server.gateway = 0");
    sleep (1);
    
    // loop through hackers
    if (mysqli_num_rows($result) > 0) {
        while ($row = mysqli_fetch_assoc($result)) {
        	if ($row['hybernate_till'] < $now) {
	            // revenue from your servers
	            $revenue = 0;
	            $rev = 0;
	            $numservers = 0;
	            // loop through servers
	            if (mysqli_num_rows($server_result) > 0) {
	                mysqli_data_seek ($server_result, 0);
	                while ($row2 = mysqli_fetch_assoc($server_result)) {
	                    if ($row2['hacker_id'] == $row['id']) {
	                    	$rev = 0;
	                        if ($row2['product_id'] == 9) $rev = $spam_rev;
	                        if ($row2['product_id'] == 14) $rev = $phishing_rev;
	                        if ($row2['product_id'] == 15) $rev = $porn_rev;
	                        if ($row2['product_id'] == 28) $rev = $filesharing_rev;
	                        if ($rev > 0) {
	                        	$numservers++;                          
	                        	$rev *= ($row2['efficiency']/100); // server efficiency
	                        	$rev = round($rev); // we like things round
		                        // if the server has a revenue virus, the revenue goes to the owner of that infection
								$virus_result = mysqli_query ($link, "SELECT hacker_id FROM infection WHERE victim_id = {$row2['id']} AND victim_entity = 'server' AND product_id = {$PRODUCT['Server Revenue Stealer']} AND spreading = 1");
								if (mysqli_num_rows($virus_result) > 0)
								{
									$steal_part = round ($rev / mysqli_num_rows($virus_result)); // divide the revenue by the number of revenue stealer infections.
		                            $rev = 0; // the original server owner gets nothing
									while ($virus_row = mysqli_fetch_assoc($virus_result))
		                            	BankTransfer($virus_row['hacker_id'], "hacker", $steal_part, "Revenue stolen by your virus from ".GetServerName($row2['id'])."({$row2['ip']})");
		                        }
		                        $revenue += $rev;
		                        $result3 = mysqli_query($link, "UPDATE server SET profit = profit + ".$rev." WHERE id = ".$row2['id']); // add to revenue counter of current server
	                        }
	                    }   
	                }
	            }
	            if ($revenue > 0) BankTransfer($row['id'], "hacker", $revenue, "Revenue generated by your ".$numservers." servers");
        	}
            // using banned ip or alias?
            if ($row['banned_date'] == 0 && !InGroup($row['id'], 1) && !InGroup($row['id'], 2) && !IsWhiteListed($row['real_ip'])) {
                    $reason = "";
                    if (IsBannedAlias($row['alias'])) $reason = "Using banned words in alias (".$row['alias'].")";
                    if (IsBlacklisted($row['real_ip'])) $reason = "Using a blacklisted ip (".$row['real_ip'].")"; 
                    if (IsBannedIP($row['real_ip'])) $reason = "Using a banned ip (".$row['real_ip'].")"; 
                    if (IsMultipleAccount($row['real_ip'])) $reason = "Multiple accounts from ip ".$row['real_ip'];
                    if ($reason != "") Ban ($row['id'], $reason, 0); 
            }
            // crash bad harddrives
            $hddhealth = GetEfficiency($row['id'], "HDD");
            if ($hddhealth > 0) {
                if ($hddhealth <= 25) AddLog ($row['id'], "hacker", "system", "S.M.A.R.T: Status BAD, Backup and Replace", $now);
                if ($hddhealth < 10) {
                    $random = mt_rand(1,100);
                    if ($random < $faulty_hdd_chance) {
                        $result2 = mysqli_query($link, "DELETE FROM system WHERE product_id NOT IN (SELECT id FROM product WHERE code = 'CPU' OR code = 'MEMORY' or code = 'MAINBOARD' or code = 'INTERNET') AND hacker_id = ".$row['id']); // hdd gone and all installed software
                        $result2 = mysqli_query($link, "DELETE FROM inventory WHERE server_id = 0 AND hacker_id = ".$row['id']); // software on it gone
                        AddLog ($row['id'], "hacker", "system", "S.M.A.R.T: Harddrive fail.", $now);
                    }   
                }
            }   
            // change the FBI server IP/Password
            $random = mt_rand(1,100);
            if ($random < $fbi_ipchange_chance) {
                $result2 = mysqli_query($link, "UPDATE hacker SET fbi_serverip = '".randomip()."' WHERE fbi_serverip_date < '$fbi_serverip_reset' AND id = ".$row['id']); 
				$result2 = mysqli_query($link, "SELECT id FROM infection WHERE victim_entity = 'server' AND victim_id == $fbi_serverid AND hacker_id = ".$row['id']); // set any fbi infections this hacker had to failed
				if ($result2 && mysqli_num_rows($result2) > 0)
					while ($row2 = mysqli_fetch_assoc($result2))
						CleanInfection ($row2['id'], "FBI scan");
            }   
            if ($random < $fbi_passwordchange_chance) {
                $result2 = mysqli_query($link, "UPDATE hacker SET fbi_serverpass = '".createrandomPassword()."' WHERE fbi_serverpass_date < '$fbi_serverpass_reset' AND id = ".$row['id']); 
            }
        }   
    }
	
	// Remove expired perks
	$before7days = date($date_format, strtotime("- $perk_expiry days"));
	$result = mysqli_query($link, "SELECT perks.hacker_id, perks.id, product.title FROM perks LEFT JOIN product ON perks.product_id = product.id WHERE perks.equip_date < '$before7days'");
	while($row = mysqli_fetch_assoc($result)) {
		SendIM(0, $row['hacker_id'], 'Perk Expired', "Your {$row['title']} perk has expired.", $now);
		RemovePerk($row['id'], "Perk Expired");
	}
	    
    // Get a new tor ip list
    //$tor_ip = file_get_contents('http://torstatus.blutmagie.de/ip_list_exit.php/Tor_ip_list_EXIT.csv');
    //file_put_contents("$gamepath/modules/tor_ip.txt", $tor_ip);
    sleep(1);
    // reset the query cache
    $result = mysqli_query($link, "FLUSH QUERY CACHE");
    AddLog (0, "hacker", "cron", "cron_1h", $now);  
?>