<img src="gfx/hacker.jpg" align="left" border="0" alt="hacker" />In this game you play a <strong><font color=lime>hacker</font></strong>. When you first log in to your hacking console
you get an email from someone you don't know, who asks you to do a hack for him because he heard great things about you. If you succeed, your name will become more known, and you will get more <strong>hacking assignments</strong>.<br>
<br>
The assignments get harder along the game. To help you in your hacking adventure, you have a full featured hacking toolbox. You have tools like: <i>ping, portscan, telnet, virus uploader, password hacker, file destroyer, etc.</i><br>
<br>
The operating system used in the game is a mix of <strong><font color=lime>*NUX</font></strong> and <strong><font color=lime>MS-DOS/Windows</font></strong>, which I called ChaOs. It has some nice features, like a <strong><font color=lime>local filesystem</font></strong> (you can add your own folders), and much more cool stuff.<br>
<br>
HackTheGame was programmed by <a href="http://www.chaozz.nl/?pageid=2">chaozz</a>.