Here you can download extra content for HackTheGame.<br />
<br />
  <table width="100%" border="1" cellpadding="3" cellspacing="0" bordercolor="#357F09">
    <tr>
     <td bgcolor="#357F09"><font color="#0A2E0E" size="2" face="fixedsys"><strong>MissionPack</td>
     <td bgcolor="#357F09"><font color="#0A2E0E" size="2" face="fixedsys"><strong>By</td>
     <td bgcolor="#357F09"><font color="#0A2E0E" size="2" face="fixedsys"><strong>Missions</td>
     <td bgcolor="#357F09"><font color="#0A2E0E" size="2" face="fixedsys"><strong>Short description</td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">Haqzor7 Challenge</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">Haqzor 7</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">6</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">MissionPack by Haqzor7</td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">Haqzor7 ChallengeTheComeback</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">Haqzor 7</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">6</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Sequel of Haqzor7</font></td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">pato2747's Mission Pack BETA</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">Pato2747</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">8</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">no description</font></td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">ssgstone's missions</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">Harrison Stone</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">6</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Based on true events of a gaming clan</font></td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">Challenge Yourself</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">Newk1991</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">8</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Missionpack by Newk1991</font></td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">FBI</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">connorman172</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">5</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Missionpack by connorman172</font></td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">Rockstars Challenge</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">R0ckst4R</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">9</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Missionpack by R0ckst4R</font></td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">steves missionpack</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">Steve</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">6</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Missionpack by Steve</font></td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">24653187s mission impossible</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">24653187</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">7</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Missionpack by 24653187</font></td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">World Tournament Hacking Quest</a></font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">rangwan kasantikul</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">17</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Missionpack by rangwan kasantikul</font></td>
    </tr>
    <tr>
     <td bgcolor="#357F09" colspan="4"><font color="#0A2E0E" size="2" face="fixedsys"><strong>Other</td>
    </tr>
    <tr bgcolor="#DFF9B3">
     <td nowrap><a href="http://www.chaozz.nl/binaries/index.php?folder=aGFja3RoZWdhbWU="><font color="#0A2E0E" size="2" face="fixedsys">HTG SoundPack by Lukanian-7</a><br />[11kb]</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">Lukanian-7</font></td>
     <td nowrap><font color="#0A2E0E" size="2" face="fixedsys">N/A</font></td>
     <td><font color="#0A2E0E" size="2" face="fixedsys">Not a missionpack, but a soundpack. Download and extract into your HackTheGame folder and overwrite the old sounds to use this</font></td>
    </tr>
  </table>
<br />
<br />
Created a MissionPack too? Send it to me: hackthegame@nospam-chaozz.nl (remove nospam-).