<img src="gfx/hackthegame119_small.jpg" align="right" border="0" alt="hackthegame" />The latest version of HackTheGame is version <b>1.21</b><br />
<br>
You can download the game on this page.<br>
Click the download link <a href="binaries/HackTheGame121.zip"><font color=lime>here</font></a>. It's a ZIP file. Just unzip and run it.<br />
<br>
<i>Supported languges: Norwegian, Dutch, English, German, Indonesian, Spanish, Frensh, Macedonian, Hungarian</i><br>