<img src="gfx/hackers.jpg" align="left" border="0" alt="hackers" />Here are a few links:<br />
<br />
<a href="http://htgmod.zxq.net/index.html"><strong><font color="lime">HTG MOD</font></strong></a> - A beautiful HTG Fansite with amazing stuff, like Video Guides of missions!! A must see!<br />
<a href="http://www.chaozz.nl/bobbert"><strong><font color="lime">Bobbert</font></strong></a> - A webcomic about two computer nerds<br />
<a href="http://www.chaozz.nl"><strong><font color="lime">chaozz@work</font></strong></a> - The developer of HackTheGame<br />
