<img src="gfx/freekevin.jpg" align="right" border="0" alt="Free Kevin!" />Hi there, welcome to the HackTheGame website, home of the freeware hacking
simulation called HackTheGame.<br>
<br>
On this website you can find everything you need to know about HackTheGame...<br>
<br>
For questions about HackTheGame, first read the <a href=?htg=faq><b><font color=lime>FAQ</font></b></a><br>
<br>
<h2>Support the game!!</h2>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
	<input type="hidden" name="cmd" value="_s-xclick">
	<input type="hidden" name="hosted_button_id" value="SF9KF63VEL4R6">
	<input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online.">
	<img alt="" border="0" src="https://www.paypalobjects.com/nl_NL/i/scr/pixel.gif" width="1" height="1">
</form>
<!--<br>
<br>
<strong><font color=lime>NEWS</font></strong><br>
<hr noshade size=1 color=lime>
<ul>
<li>28-okt-08 - Check out <a href="http://uk.youtube.com/watch?v=yfGPGs2foto">this amazing HTG review</a>!</li>
<li>HackTheGame 2 news: HTG2:HackerForever will be an MMORPG, like Mobstar.</li>
<li><font color="lime">01-jun-08 > HackTheGame now has a forum!!! Join now and discuss the new version or ask support! <a href="http://www.hackerforever.com/hf/forum/index.php?board=11.0">Go here</a></font></li>
<li>26-mar-08 > 1 new missionpack added</li>
<li>20-feb-08 > 1 new missionpack added</li>
<li>13-feb-08 > 4 new missionpacks added + I added hungarian language files to HackTheGame 1.21</li>
<li>24-jun-07 > Added a new section to the homepage: MissionPacks. The place for extra content!</li>
<li>27-may-07 > HackTheGame 1.21 is released. Fixed are: email title and sender, missionpack editor bug (random_logon/random_login), macedonian language added</li>
<li>12-may-07 > HackTheGame 1.20 is released. It now includes a mission pack editor/creator. So you can make the game longer, add mission packs and share them. Let the HackTheGame revolution begin ;-)</li>
</ul>//-->