<strong><font color=lime>NEWS</font></strong>
<hr noshade size=1 color=lime>
<ul>
<li>04-may-07 > released <a href="http://www.chaozz.nl/hackthegame/?htg=screenshots">a screenshot</a> of the upcoming MissionPack editor
<li>13-okt-06 > released version 1.19. new interface, norwegian support and bugfixes</li>
<li>17-aug-06 > working on a level editor, so you can make selfmade mission packs</li>
<li>19-apr-06 > version 1.18 released. copyfile bugfix, translation fixes and more. see changelog</li>
<li>08-apr-06 > switched to the spanish version of Scancode</li>
<li>07-apr-06 > bug fixed in Spanish version, redownload 1.16 if you have missing IP problems</li>
<li>07-apr-06 > version 1.16 released, with new language and some fixes</li>
<li>16-mar-06 > bugfixes and more bugfixes. Last version is 1.15</li>
<li>15-mar-06 > NEW VERSION IS DOWNLOADABLE NOW!</li>
<li>09-mar-06 > I now have complete translations in German, Spanish, English and Dutch.</li>
<li>06-nov-05 > I added a preview screenshot of <a href=?htg=screenshots>the Dutch translation of HTG</a></li>
<li>31-okt-05 > scancode made an awesome intro for this HTG page. See it <a href=intro.htm>here</a>!</li>
<li>10-okt-05 > The game is currently being translated to German, Spanish and Dutch</li>
<li>01-okt-05 > The hiscore upload is temporarely DISABLED. It's back up in no time</li>
</ul>