<div align="center">
 <a href=?htg=showgfx&gfx=missionpackeditor1.jpg><img src="gfx/missionpackeditor1_small.jpg" border="0">
 Early preview of the upcoming MissionPack Editor</a>
 
 <a href=?htg=showgfx&gfx=hackthegame119.jpg><img src="gfx/hackthegame119_small.jpg" border="0">
 Main console v1.19</a>
 
 <a href=?htg=showgfx&gfx=screenshot1.jpg><img src="gfx/screenshot1_s.jpg" border="0">
 Main console v1.18 (and lower)</a>
 
 <a href=?htg=showgfx&gfx=screenshot2.jpg><img src="gfx/screenshot2_s.jpg" border="0">
 Dutch v1.18</a>
 
</div>

More screenshots coming soon..
Have you got a great HackTheGame screenshot? <a href="mailto:chaozz@hackthegame.com?subject=HTG Screenshot">Send them to me</a>